-- Phase 3: trust, reputation, reporting, and community moderation.

create or replace view public.profile_reputation
with (security_invoker = true)
as
with post_stats as (
  select
    p.user_id,
    count(*)::bigint as post_count,
    coalesce(sum(v.score), 0)::bigint as post_score
  from public.posts p
  left join (
    select post_id, sum(vote)::bigint as score
    from public.votes
    group by post_id
  ) v on v.post_id = p.id
  where p.user_id is not null
  group by p.user_id
),
comment_stats as (
  select
    c.user_id,
    count(*)::bigint as comment_count,
    coalesce(sum(v.score), 0)::bigint as comment_score
  from public.comments c
  left join (
    select comment_id, sum(vote)::bigint as score
    from public.comment_votes
    group by comment_id
  ) v on v.comment_id = c.id
  where c.user_id is not null
  group by c.user_id
)
select
  p.id as user_id,
  coalesce(ps.post_count, 0)::bigint as post_count,
  coalesce(cs.comment_count, 0)::bigint as comment_count,
  coalesce(ps.post_score, 0)::bigint as post_score,
  coalesce(cs.comment_score, 0)::bigint as comment_score,
  (coalesce(ps.post_score, 0) + coalesce(cs.comment_score, 0))::bigint as yap_score
from public.profiles p
left join post_stats ps on ps.user_id = p.id
left join comment_stats cs on cs.user_id = p.id;

grant select on public.profile_reputation to anon, authenticated;

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid not null references auth.users(id) on delete cascade,
  community_id bigint not null references public.communities(id) on delete cascade,
  target_type text not null,
  target_id bigint not null,
  reason text not null,
  details text not null default '',
  status text not null default 'open',
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references auth.users(id) on delete set null,
  resolution_note text not null default '',
  constraint reports_target_type_check check (target_type in ('post', 'comment')),
  constraint reports_reason_check check (reason in ('spam', 'harassment', 'hate', 'misinformation', 'off_topic', 'other')),
  constraint reports_status_check check (status in ('open', 'reviewing', 'resolved', 'dismissed')),
  constraint reports_details_length_check check (char_length(details) <= 1200),
  constraint reports_resolution_note_length_check check (char_length(resolution_note) <= 1200)
);

create unique index if not exists reports_one_active_per_reporter_target_idx
  on public.reports (reporter_id, target_type, target_id)
  where status in ('open', 'reviewing');
create index if not exists reports_community_status_created_idx
  on public.reports (community_id, status, created_at desc);
create index if not exists reports_reporter_created_idx
  on public.reports (reporter_id, created_at desc);
create index if not exists reports_reviewed_by_idx
  on public.reports (reviewed_by);

alter table public.reports enable row level security;
grant select, insert, update on public.reports to authenticated;
grant usage, select on sequence public.reports_id_seq to authenticated;

drop policy if exists "Users can submit reports" on public.reports;
create policy "Users can submit reports"
on public.reports for insert
to authenticated
with check (
  (select auth.uid()) = reporter_id
  and (
    (
      target_type = 'post'
      and exists (
        select 1 from public.posts p
        where p.id = target_id
          and p.community_id = reports.community_id
      )
    )
    or
    (
      target_type = 'comment'
      and exists (
        select 1
        from public.comments c
        join public.posts p on p.id = c.post_id
        where c.id = target_id
          and p.community_id = reports.community_id
      )
    )
  )
);

drop policy if exists "Users and community managers can read reports" on public.reports;
create policy "Users and community managers can read reports"
on public.reports for select
to authenticated
using (
  reporter_id = (select auth.uid())
  or exists (
    select 1 from public.communities c
    where c.id = reports.community_id
      and c.created_by = (select auth.uid())
  )
  or exists (
    select 1 from public.community_members cm
    where cm.community_id = reports.community_id
      and cm.user_id = (select auth.uid())
      and cm.role = 'moderator'
      and cm.banned = false
  )
);

drop policy if exists "Community managers can update reports" on public.reports;
create policy "Community managers can update reports"
on public.reports for update
to authenticated
using (
  exists (
    select 1 from public.communities c
    where c.id = reports.community_id
      and c.created_by = (select auth.uid())
  )
  or exists (
    select 1 from public.community_members cm
    where cm.community_id = reports.community_id
      and cm.user_id = (select auth.uid())
      and cm.role = 'moderator'
      and cm.banned = false
  )
)
with check (
  exists (
    select 1 from public.communities c
    where c.id = reports.community_id
      and c.created_by = (select auth.uid())
  )
  or exists (
    select 1 from public.community_members cm
    where cm.community_id = reports.community_id
      and cm.user_id = (select auth.uid())
      and cm.role = 'moderator'
      and cm.banned = false
  )
);

create table if not exists public.moderation_log (
  id bigint generated by default as identity primary key,
  community_id bigint not null references public.communities(id) on delete cascade,
  actor_id uuid not null references auth.users(id) on delete cascade,
  action_type text not null,
  target_type text not null,
  target_id bigint,
  note text not null default '',
  created_at timestamptz not null default now(),
  constraint moderation_log_action_type_check check (action_type in ('report_resolved', 'report_dismissed', 'post_removed', 'comment_removed', 'member_muted', 'member_unmuted', 'member_banned', 'member_unbanned')),
  constraint moderation_log_target_type_check check (target_type in ('report', 'post', 'comment', 'member')),
  constraint moderation_log_note_length_check check (char_length(note) <= 1200)
);

create index if not exists moderation_log_community_created_idx
  on public.moderation_log (community_id, created_at desc);
create index if not exists moderation_log_actor_created_idx
  on public.moderation_log (actor_id, created_at desc);

alter table public.moderation_log enable row level security;
grant select, insert on public.moderation_log to authenticated;
grant usage, select on sequence public.moderation_log_id_seq to authenticated;

drop policy if exists "Community managers can read moderation log" on public.moderation_log;
create policy "Community managers can read moderation log"
on public.moderation_log for select
to authenticated
using (
  exists (
    select 1 from public.communities c
    where c.id = moderation_log.community_id
      and c.created_by = (select auth.uid())
  )
  or exists (
    select 1 from public.community_members cm
    where cm.community_id = moderation_log.community_id
      and cm.user_id = (select auth.uid())
      and cm.role = 'moderator'
      and cm.banned = false
  )
);

drop policy if exists "Community managers can write moderation log" on public.moderation_log;
create policy "Community managers can write moderation log"
on public.moderation_log for insert
to authenticated
with check (
  actor_id = (select auth.uid())
  and (
    exists (
      select 1 from public.communities c
      where c.id = moderation_log.community_id
        and c.created_by = (select auth.uid())
    )
    or exists (
      select 1 from public.community_members cm
      where cm.community_id = moderation_log.community_id
        and cm.user_id = (select auth.uid())
        and cm.role = 'moderator'
        and cm.banned = false
    )
  )
);

drop policy if exists "Users can delete their own posts" on public.posts;
drop policy if exists "Community managers can delete posts" on public.posts;
drop policy if exists "Users or community managers can delete posts" on public.posts;
create policy "Users or community managers can delete posts"
on public.posts for delete
to authenticated
using (
  user_id = (select auth.uid())
  or exists (
    select 1 from public.communities c
    where c.id = posts.community_id
      and c.created_by = (select auth.uid())
  )
  or exists (
    select 1 from public.community_members cm
    where cm.community_id = posts.community_id
      and cm.user_id = (select auth.uid())
      and cm.role = 'moderator'
      and cm.banned = false
  )
);

drop policy if exists "Users can delete their own comments" on public.comments;
drop policy if exists "Community managers can delete comments" on public.comments;
drop policy if exists "Users or community managers can delete comments" on public.comments;
create policy "Users or community managers can delete comments"
on public.comments for delete
to authenticated
using (
  user_id = (select auth.uid())
  or exists (
    select 1
    from public.posts p
    join public.communities c on c.id = p.community_id
    where p.id = comments.post_id
      and c.created_by = (select auth.uid())
  )
  or exists (
    select 1
    from public.posts p
    join public.community_members cm on cm.community_id = p.community_id
    where p.id = comments.post_id
      and cm.user_id = (select auth.uid())
      and cm.role = 'moderator'
      and cm.banned = false
  )
);
