create table public.poll_options (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  option_text text not null,
  position integer not null default 0,
  created_at timestamptz not null default now(),
  constraint poll_options_text_length check (char_length(btrim(option_text)) between 1 and 120),
  constraint poll_options_id_post_unique unique (id, post_id)
);

create table public.poll_votes (
  post_id bigint not null references public.posts(id) on delete cascade,
  option_id bigint not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (post_id, user_id),
  constraint poll_votes_option_post_fk foreign key (option_id, post_id)
    references public.poll_options(id, post_id) on delete cascade
);

create index poll_options_post_idx on public.poll_options(post_id, position, id);
create index poll_votes_option_idx on public.poll_votes(option_id);
create index poll_votes_user_idx on public.poll_votes(user_id);
create index if not exists saved_posts_post_id_idx on public.saved_posts(post_id);

alter table public.poll_options enable row level security;
alter table public.poll_votes enable row level security;

grant select on public.poll_options, public.poll_votes to anon, authenticated;
grant insert on public.poll_options to authenticated;
grant insert, update, delete on public.poll_votes to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists "Anyone can read poll options" on public.poll_options;
create policy "Anyone can read poll options"
on public.poll_options for select
to anon, authenticated
using (true);

drop policy if exists "Post authors can create poll options" on public.poll_options;
create policy "Post authors can create poll options"
on public.poll_options for insert
to authenticated
with check (
  exists (
    select 1 from public.posts p
    where p.id = poll_options.post_id
      and p.user_id = (select auth.uid())
      and p.post_type = 'poll'
  )
);

drop policy if exists "Anyone can read poll votes" on public.poll_votes;
create policy "Anyone can read poll votes"
on public.poll_votes for select
to anon, authenticated
using (true);

drop policy if exists "Users can vote in polls" on public.poll_votes;
create policy "Users can vote in polls"
on public.poll_votes for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can change their poll vote" on public.poll_votes;
create policy "Users can change their poll vote"
on public.poll_votes for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can remove their poll vote" on public.poll_votes;
create policy "Users can remove their poll vote"
on public.poll_votes for delete
to authenticated
using ((select auth.uid()) = user_id);
