alter table public.posts
  add column user_id uuid references auth.users(id) on delete set null default auth.uid(),
  add column post_type text not null default 'text',
  add column link_url text;

update public.posts
set post_type = 'image'
where image_url is not null and btrim(image_url) <> '';

alter table public.posts
  add constraint posts_post_type_check check (post_type in ('text', 'image', 'link', 'poll'));

create index posts_user_id_idx on public.posts(user_id);
create index posts_created_at_idx on public.posts(created_at desc);
create index posts_community_created_at_idx on public.posts(community_id, created_at desc);

create table public.post_flairs (
  id bigint generated by default as identity primary key,
  community_id bigint not null references public.communities(id) on delete cascade,
  name text not null,
  color text not null default '#7c3aed',
  position integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint post_flairs_name_length check (char_length(btrim(name)) between 1 and 40),
  constraint post_flairs_unique_name unique (community_id, name)
);

alter table public.posts
  add column flair_id bigint references public.post_flairs(id) on delete set null;
create index posts_flair_id_idx on public.posts(flair_id);
create index post_flairs_community_idx on public.post_flairs(community_id, position, id);

create table public.community_rules (
  id bigint generated by default as identity primary key,
  community_id bigint not null references public.communities(id) on delete cascade,
  title text not null,
  description text not null default '',
  position integer not null default 0,
  created_at timestamptz not null default now(),
  constraint community_rules_title_length check (char_length(btrim(title)) between 1 and 120)
);
create index community_rules_community_idx on public.community_rules(community_id, position, id);

create table public.saved_posts (
  user_id uuid not null references auth.users(id) on delete cascade,
  post_id bigint not null references public.posts(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, post_id)
);
create index saved_posts_user_created_idx on public.saved_posts(user_id, created_at desc);

create table public.comment_votes (
  id bigint generated by default as identity primary key,
  comment_id bigint not null references public.comments(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  vote integer not null,
  created_at timestamptz not null default now(),
  constraint comment_votes_value_check check (vote in (-1, 1)),
  constraint comment_votes_one_per_user unique (comment_id, user_id)
);
create index comment_votes_comment_idx on public.comment_votes(comment_id);
create index comment_votes_user_idx on public.comment_votes(user_id);

alter table public.post_flairs enable row level security;
alter table public.community_rules enable row level security;
alter table public.saved_posts enable row level security;
alter table public.comment_votes enable row level security;

grant select on public.post_flairs, public.community_rules, public.comment_votes to anon, authenticated;
grant insert, update, delete on public.post_flairs, public.community_rules to authenticated;
grant select, insert, delete on public.saved_posts to authenticated;
grant insert, update, delete on public.comment_votes to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant select on public.saved_posts to authenticated;
grant update, delete on public.posts to authenticated;

drop policy if exists "Anyone can read post flairs" on public.post_flairs;
create policy "Anyone can read post flairs"
on public.post_flairs for select
to anon, authenticated
using (true);

drop policy if exists "Community admins can create post flairs" on public.post_flairs;
create policy "Community admins can create post flairs"
on public.post_flairs for insert
to authenticated
with check (
  public.is_community_owner(community_id, (select auth.uid()))
  or public.is_community_moderator(community_id)
);

drop policy if exists "Community admins can update post flairs" on public.post_flairs;
create policy "Community admins can update post flairs"
on public.post_flairs for update
to authenticated
using (
  public.is_community_owner(community_id, (select auth.uid()))
  or public.is_community_moderator(community_id)
)
with check (
  public.is_community_owner(community_id, (select auth.uid()))
  or public.is_community_moderator(community_id)
);

drop policy if exists "Community admins can delete post flairs" on public.post_flairs;
create policy "Community admins can delete post flairs"
on public.post_flairs for delete
to authenticated
using (
  public.is_community_owner(community_id, (select auth.uid()))
  or public.is_community_moderator(community_id)
);

drop policy if exists "Anyone can read community rules" on public.community_rules;
create policy "Anyone can read community rules"
on public.community_rules for select
to anon, authenticated
using (true);

drop policy if exists "Community admins can create rules" on public.community_rules;
create policy "Community admins can create rules"
on public.community_rules for insert
to authenticated
with check (
  public.is_community_owner(community_id, (select auth.uid()))
  or public.is_community_moderator(community_id)
);

drop policy if exists "Community admins can update rules" on public.community_rules;
create policy "Community admins can update rules"
on public.community_rules for update
to authenticated
using (
  public.is_community_owner(community_id, (select auth.uid()))
  or public.is_community_moderator(community_id)
)
with check (
  public.is_community_owner(community_id, (select auth.uid()))
  or public.is_community_moderator(community_id)
);

drop policy if exists "Community admins can delete rules" on public.community_rules;
create policy "Community admins can delete rules"
on public.community_rules for delete
to authenticated
using (
  public.is_community_owner(community_id, (select auth.uid()))
  or public.is_community_moderator(community_id)
);

drop policy if exists "Users can read their saved posts" on public.saved_posts;
create policy "Users can read their saved posts"
on public.saved_posts for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users can save posts" on public.saved_posts;
create policy "Users can save posts"
on public.saved_posts for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can unsave posts" on public.saved_posts;
create policy "Users can unsave posts"
on public.saved_posts for delete
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Anyone can read comment votes" on public.comment_votes;
create policy "Anyone can read comment votes"
on public.comment_votes for select
to anon, authenticated
using (true);

drop policy if exists "Users can create comment votes" on public.comment_votes;
create policy "Users can create comment votes"
on public.comment_votes for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update their comment votes" on public.comment_votes;
create policy "Users can update their comment votes"
on public.comment_votes for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete their comment votes" on public.comment_votes;
create policy "Users can delete their comment votes"
on public.comment_votes for delete
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Authenticated users can create posts" on public.posts;
create policy "Authenticated users can create posts"
on public.posts for insert
to authenticated
with check (
  (select auth.uid()) = user_id
  and (
    public.is_community_owner(community_id, (select auth.uid()))
    or exists (
      select 1
      from public.community_members cm
      where cm.community_id = posts.community_id
        and cm.user_id = (select auth.uid())
        and cm.banned = false
        and cm.muted = false
    )
  )
);

drop policy if exists "Users can update their own posts" on public.posts;
create policy "Users can update their own posts"
on public.posts for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete their own posts" on public.posts;
create policy "Users can delete their own posts"
on public.posts for delete
to authenticated
using ((select auth.uid()) = user_id);

drop function if exists public.get_posts_with_counts();
create function public.get_posts_with_counts()
returns table(
  id bigint,
  title text,
  content text,
  created_at timestamptz,
  image_url text,
  like_count integer,
  comment_count integer,
  user_avatar_url text
)
language sql
stable
security invoker
set search_path = public
as $$
  select
    p.id,
    p.title,
    p.content,
    p.created_at,
    p.image_url,
    coalesce((select sum(v.vote)::integer from public.votes v where v.post_id = p.id), 0),
    (select count(*)::integer from public.comments c where c.post_id = p.id),
    p.avatar_url
  from public.posts p
  order by p.created_at desc;
$$;

grant execute on function public.get_posts_with_counts() to anon, authenticated;
