-- Phase 4: follows, private 1:1 messaging, follow notifications, mentions, and Realtime message delivery.

create table if not exists public.user_follows (
  follower_id uuid not null references public.profiles(id) on delete cascade,
  following_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (follower_id, following_id),
  constraint user_follows_no_self check (follower_id <> following_id)
);

create index if not exists user_follows_following_idx on public.user_follows(following_id, created_at desc);
create index if not exists user_follows_follower_idx on public.user_follows(follower_id, created_at desc);

alter table public.user_follows enable row level security;

drop policy if exists "Public can view follows" on public.user_follows;
create policy "Public can view follows"
on public.user_follows for select
to anon, authenticated
using (true);

drop policy if exists "Users can follow people" on public.user_follows;
create policy "Users can follow people"
on public.user_follows for insert
to authenticated
with check ((select auth.uid()) = follower_id and follower_id <> following_id);

drop policy if exists "Users can unfollow people" on public.user_follows;
create policy "Users can unfollow people"
on public.user_follows for delete
to authenticated
using ((select auth.uid()) = follower_id);

grant select on public.user_follows to anon, authenticated;
grant insert, delete on public.user_follows to authenticated;

create table if not exists public.direct_conversations (
  id bigint generated by default as identity primary key,
  user_low uuid not null references public.profiles(id) on delete cascade,
  user_high uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  last_message_at timestamptz not null default now(),
  constraint direct_conversations_distinct_users check (user_low <> user_high),
  constraint direct_conversations_sorted_users check (user_low::text < user_high::text),
  constraint direct_conversations_unique_pair unique (user_low, user_high)
);

create index if not exists direct_conversations_low_recent_idx on public.direct_conversations(user_low, last_message_at desc);
create index if not exists direct_conversations_high_recent_idx on public.direct_conversations(user_high, last_message_at desc);

alter table public.direct_conversations enable row level security;

drop policy if exists "Participants can view conversations" on public.direct_conversations;
create policy "Participants can view conversations"
on public.direct_conversations for select
to authenticated
using ((select auth.uid()) = user_low or (select auth.uid()) = user_high);

drop policy if exists "Participants can create conversations" on public.direct_conversations;
create policy "Participants can create conversations"
on public.direct_conversations for insert
to authenticated
with check (
  ((select auth.uid()) = user_low or (select auth.uid()) = user_high)
  and user_low <> user_high
  and user_low::text < user_high::text
);

drop policy if exists "Participants can update conversation recency" on public.direct_conversations;
create policy "Participants can update conversation recency"
on public.direct_conversations for update
to authenticated
using ((select auth.uid()) = user_low or (select auth.uid()) = user_high)
with check ((select auth.uid()) = user_low or (select auth.uid()) = user_high);

grant select, insert on public.direct_conversations to authenticated;
grant update(last_message_at) on public.direct_conversations to authenticated;

create table if not exists public.direct_messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.direct_conversations(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now(),
  read_at timestamptz,
  constraint direct_messages_body_length check (char_length(btrim(body)) between 1 and 4000)
);

create index if not exists direct_messages_conversation_recent_idx on public.direct_messages(conversation_id, created_at desc);
create index if not exists direct_messages_sender_idx on public.direct_messages(sender_id, created_at desc);
create index if not exists direct_messages_unread_idx on public.direct_messages(conversation_id, read_at) where read_at is null;

alter table public.direct_messages enable row level security;

drop policy if exists "Participants can view messages" on public.direct_messages;
create policy "Participants can view messages"
on public.direct_messages for select
to authenticated
using (
  exists (
    select 1 from public.direct_conversations c
    where c.id = direct_messages.conversation_id
      and ((select auth.uid()) = c.user_low or (select auth.uid()) = c.user_high)
  )
);

drop policy if exists "Participants can send messages" on public.direct_messages;
create policy "Participants can send messages"
on public.direct_messages for insert
to authenticated
with check (
  sender_id = (select auth.uid())
  and exists (
    select 1 from public.direct_conversations c
    where c.id = direct_messages.conversation_id
      and ((select auth.uid()) = c.user_low or (select auth.uid()) = c.user_high)
  )
);

drop policy if exists "Recipients can mark messages read" on public.direct_messages;
create policy "Recipients can mark messages read"
on public.direct_messages for update
to authenticated
using (
  sender_id <> (select auth.uid())
  and exists (
    select 1 from public.direct_conversations c
    where c.id = direct_messages.conversation_id
      and ((select auth.uid()) = c.user_low or (select auth.uid()) = c.user_high)
  )
)
with check (
  sender_id <> (select auth.uid())
  and exists (
    select 1 from public.direct_conversations c
    where c.id = direct_messages.conversation_id
      and ((select auth.uid()) = c.user_low or (select auth.uid()) = c.user_high)
  )
);

grant select, insert on public.direct_messages to authenticated;
grant update(read_at) on public.direct_messages to authenticated;

create or replace function public.get_or_create_direct_conversation(p_other_user uuid)
returns bigint
language plpgsql
security invoker
set search_path = public
as $$
declare
  current_user_id uuid := (select auth.uid());
  low_user uuid;
  high_user uuid;
  conversation_id bigint;
begin
  if current_user_id is null then raise exception 'Authentication required'; end if;
  if p_other_user is null or p_other_user = current_user_id then raise exception 'Choose another Yapster member'; end if;
  if not exists (select 1 from public.profiles where id = p_other_user) then raise exception 'Profile not found'; end if;

  if current_user_id::text < p_other_user::text then
    low_user := current_user_id;
    high_user := p_other_user;
  else
    low_user := p_other_user;
    high_user := current_user_id;
  end if;

  insert into public.direct_conversations(user_low, user_high)
  values (low_user, high_user)
  on conflict (user_low, user_high) do nothing;

  select id into conversation_id
  from public.direct_conversations
  where user_low = low_user and user_high = high_user;

  return conversation_id;
end;
$$;

revoke all on function public.get_or_create_direct_conversation(uuid) from public, anon;
grant execute on function public.get_or_create_direct_conversation(uuid) to authenticated;

create or replace function public.mark_direct_conversation_read(p_conversation_id bigint)
returns void
language sql
security invoker
set search_path = public
as $$
  update public.direct_messages
  set read_at = coalesce(read_at, now())
  where conversation_id = p_conversation_id
    and sender_id <> (select auth.uid())
    and read_at is null;
$$;

revoke all on function public.mark_direct_conversation_read(bigint) from public, anon;
grant execute on function public.mark_direct_conversation_read(bigint) to authenticated;

create or replace function public.touch_direct_conversation()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.direct_conversations set last_message_at = new.created_at where id = new.conversation_id;
  return new;
end;
$$;

revoke all on function public.touch_direct_conversation() from public, anon, authenticated;
drop trigger if exists direct_message_touch_conversation on public.direct_messages;
create trigger direct_message_touch_conversation after insert on public.direct_messages for each row execute function public.touch_direct_conversation();

create or replace function public.create_follow_notification()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare actor_name text;
begin
  select coalesce(nullif(display_name, ''), nullif(username, ''), 'Someone') into actor_name from public.profiles where id = new.follower_id;
  insert into public.notifications(recipient_id, actor_id, type, message, read, created_at)
  values (new.following_id, new.follower_id, 'user_follow', actor_name || ' followed you.', false, now());
  return new;
end;
$$;

revoke all on function public.create_follow_notification() from public, anon, authenticated;
drop trigger if exists user_follow_notification on public.user_follows;
create trigger user_follow_notification after insert on public.user_follows for each row execute function public.create_follow_notification();

create or replace function public.create_mention_notifications()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  source_text text;
  actor_user_id uuid;
  target_post_id bigint;
  target_comment_id bigint;
  target_community_id bigint;
  mentioned_username text;
  mentioned_profile record;
  actor_name text;
begin
  if tg_table_name = 'posts' then
    source_text := coalesce(new.title, '') || ' ' || coalesce(new.content, '');
    actor_user_id := new.user_id;
    target_post_id := new.id;
    target_comment_id := null;
    target_community_id := new.community_id;
  elsif tg_table_name = 'comments' then
    source_text := coalesce(new.content, '');
    actor_user_id := new.user_id;
    target_post_id := new.post_id;
    target_comment_id := new.id;
    select community_id into target_community_id from public.posts where id = new.post_id;
  else
    return new;
  end if;

  if actor_user_id is null or source_text is null or position('@' in source_text) = 0 then return new; end if;
  select coalesce(nullif(display_name, ''), nullif(username, ''), 'Someone') into actor_name from public.profiles where id = actor_user_id;

  for mentioned_username in
    select distinct lower((matches)[2])
    from regexp_matches(source_text, '(^|[^A-Za-z0-9_])@([A-Za-z0-9_]{1,30})', 'g') as matches
  loop
    for mentioned_profile in
      select id, username from public.profiles where lower(username) = mentioned_username and id <> actor_user_id
    loop
      if not exists (
        select 1 from public.notifications n
        where n.recipient_id = mentioned_profile.id
          and n.actor_id = actor_user_id
          and n.type = 'mention'
          and n.post_id is not distinct from target_post_id
          and n.comment_id is not distinct from target_comment_id
      ) then
        insert into public.notifications(recipient_id, actor_id, type, post_id, comment_id, community_id, message, read, created_at)
        values (mentioned_profile.id, actor_user_id, 'mention', target_post_id, target_comment_id, target_community_id, actor_name || ' mentioned you.', false, now());
      end if;
    end loop;
  end loop;
  return new;
end;
$$;

revoke all on function public.create_mention_notifications() from public, anon, authenticated;
drop trigger if exists post_mention_notifications on public.posts;
create trigger post_mention_notifications after insert on public.posts for each row execute function public.create_mention_notifications();
drop trigger if exists comment_mention_notifications on public.comments;
create trigger comment_mention_notifications after insert on public.comments for each row execute function public.create_mention_notifications();

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'direct_messages'
  ) then
    alter publication supabase_realtime add table public.direct_messages;
  end if;
end $$;
